repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: 'poetry.lock'
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
      args: [--fix, --show-fixes]
